# Generated by Django 3.2.4 on 2021-07-17 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0007_post_dislikes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='dislikes',
        ),
    ]
