# Generated by Django 3.2.4 on 2021-07-17 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0008_remove_post_dislikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislikes',
            field=models.ManyToManyField(related_name='dislike_blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
