# Generated by Django 3.2.4 on 2021-07-20 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0010_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click above to see Blog Post...', max_length=255),
        ),
    ]
