# Generated by Django 3.2.4 on 2021-07-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/default_pic.jpg/', null=True, upload_to='images/profile/'),
        ),
    ]
